version: '3.8'

services:
  pdfchat:
    build: .
    container_name: pdf-chat-service
    ports:
      - "8000:8000"
    volumes:
      - ./uploaded:/app/uploaded
    environment:
      - PYTHONUNBUFFERED=1
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
